GET http://192.168.43.153:2020/allData

###
# GET http://192.168.1.6:2020/gallery/guru
GET http://192.168.1.4:2020/gallery/image1.jpg
###
//Send SMS Test
POST  http://192.168.1.18:2020/contact/sms
content-type: application/json

{
    "account_id":123456,
    "sender":"TXTLCL",
    "message" : "Hello",
    "number":"918220675811"
}
###
//Get Feedback 
POST http://192.168.1.9:2020/contact/GetFeedback
content-type: application/json

{
    "name":"hari",
    "email":"hari@g.in"
}

###
//Image Upload
POST http://192.168.43.153:2020/upload_slider
content-type: application/json